### ISSUE TITLE
[Missing Geographies] Search + Filter Box

### ISSUE THREAD

**Issue by rxun** [jenki415/EEO_Civic_Fellows_2021#3]
**Description**: Currently, the user types in a CSA name directly into the text input box then retrieves any matching county components. However, users may be unaware about how to write and format their response, and some may prefer to scroll and find the CSA themselves.
- Replace the text input with a search box
- List all the potential CSAs directly below
- Filter the results as user continues to type
- MAYBE: add a quick search
- MAYBE: display suggested CSAs / predict potential responses as user is typing
- EXAMPLE FUNCTIONALITY: 

![Screenshot from 2021-07-08 12-55-52](https://user-images.githubusercontent.com/19174670/124982990-42beab80-dfec-11eb-88b0-74d548494541.png)

**Comment by KTaylor8** [comment]
Using
https://github.com/danielfarrell/bootstrap-combobox
